## Matplotlib  한글 사용하기



In [2]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

In [15]:
import numpy as np

np.random.seed(9)

In [16]:
# [0., 1.)까지의 난수를 50개 생성하고 여기에 100을 곱해 [0., 100.) 인 난수 생성
# 순서대로 정렬
# R의 order()와 같은 argsort(x) 함수가 있음
randflt = np.sort( np.random.random(50) * 100 )
randflt

array([ 1.03741539,  3.87483758,  3.94548177,  8.40596512, 13.3829529 ,
       14.21110855, 16.67763465, 16.96362576, 18.55416869, 18.73586471,
       21.85586756, 24.31156753, 24.81011684, 34.54986401, 34.69019538,
       38.64771696, 41.85081805, 43.55554648, 46.3534714 , 46.56684754,
       47.79740135, 49.57732931, 49.62817177, 50.18745921, 52.10847115,
       54.7837783 , 57.27598156, 61.05377408, 64.95404632, 66.68989729,
       68.76740932, 69.44386778, 69.91073914, 70.24274241, 70.35291738,
       75.82779868, 80.373977  , 82.48704645, 86.08319232, 87.04082964,
       87.34008431, 87.85590855, 89.80071182, 90.62772769, 92.52000773,
       94.05244095, 94.5517417 , 95.09640316, 97.08460121, 98.33592482])

In [23]:
# numpy random number generator 
# https://docs.scipy.org/doc/numpy/reference/routines.random.html
# RandomState : Container for the Mersenne Twister pseudo-random number generator.
rn = np.random.RandomState(4)
x = rn.randint(0, 10, (4, 6))
print(x)

[[7 5 1 8 7 8]
 [2 9 7 7 7 9]
 [8 4 2 6 4 3]
 [0 7 5 5 9 6]]


In [25]:
# sort each column of X
np.sort(x, axis=0)

array([[0, 4, 1, 5, 4, 3],
       [2, 5, 2, 6, 7, 6],
       [7, 7, 5, 7, 7, 8],
       [8, 9, 7, 8, 9, 9]])

In [26]:
np.sort(x, axis=1)

array([[1, 5, 7, 7, 8, 8],
       [2, 7, 7, 7, 9, 9],
       [2, 3, 4, 4, 6, 8],
       [0, 5, 5, 6, 7, 9]])